// This gulp asset pipeline supports linting of scss and js files along with
// compiling and bundling css and js files into static/assets/ directories to
// be used by Hugo.

// Bring in individual gulp configs
require('./config/gulp/flags');
require('./config/gulp/styles');
require('./config/gulp/scripts');
require('./config/gulp/images');
require('./config/gulp/fonts');
require('./config/gulp/data');
require('./config/gulp/deploy');
var build = require('./config/gulp/build');
var gulp = require('gulp');
var log = require('fancy-log');
var colors = require('ansi-colors');

gulp.task('default', function (done) {
  build.printPackageInfo(done);
  log('Available tasks');
  log('$', colors.magenta('gulp watch'));
  log('Watch for changes. Note: must run gulp website in new terminal to view changes');
  log('$', colors.magenta('gulp build'));
  log('Build the asset-pipeline with optional production and no-test flags');
  log('$', colors.magenta('gulp cleanAll'));
  log('Removes files and directories generated by gulp');
  log('$', colors.magenta('gulp website'));
  log('Runs the gulp watch and hugo serve');
  log('$', colors.magenta('gulp buildWebsite'));
  log('Build the asset-pipeline and the website using Hugo. Note: run hugo server to view site ');
  done();
});

gulp.task('test', gulp.series('eslint', 'scss-lint'), function (done) {
  build.printPackageInfo();
  done();
})
