name: Cypress - link validator testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LANG: en_US.UTF-8
      LANGUAGE: en_US
      LC_ALL: en_US.UTF-8

    steps:
      - name: Checkout source.
        uses: actions/checkout@v2

      - name: Install node.js.
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install NPM dependencies.
        run: npm install

      - name: Build and start up hugo server.
        run: npm run build && npm run start & sleep 30s

      - name: Run Cypress Link Validator test.
        run: npm run cy:links
